version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 9000 --reload"
    volumes:
      - ./app:/app
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb
    networks:
      - my_network


  postgres:
    image: postgres:14
    container_name: postgresdb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:
    driver: local

networks:
  my_network:
    driver: bridge
